/*console.LOG("") É UM COMANDO USADO PARA MOSTRAR MENSAGENS NO CONSOLE DO NAVEGADOR PARA FINS DE DEPURAÇÃO E TESTES. 
ELE NÃO EXIBE MENSAGENS NA PÁGINA DA WEB.*/

console.log("Arquivo.js carregado com sucesso!");

/* VARIÁVEIS NÃO PODEM TER NUMEROS NO INÍCIO DO NOME E NÃO PODEM TER MESMO NOME OU NOMES REPETIDOS.
NÃO PODE TER ESPAÇOS NO NOME DA VARIÁVEL
-NÃO PODEM CONTER CARACTERES ESPECIAIS (EXCETO _ E $)
-PALAVRAS RESERVADAS NÃO PODEM SER USADAS COMO NOMES DE VARIÁVEIS
-EXEMPLOS DE PALAVRAS RESERVADAS:
-function
-if
-let É UMA PALAVRA RESERVADA USADA PARA DECLARAR VARIÁVEIS COM ESCOPO DE BLOCO, QUE PERMITE MUDAR O VALOR DA VARIÁVEL AO LONGO DO TEMPO.
-const É UMA PALAVRA RESERVADA USADA PARA DECLARAR VARIÁVEIS CUJO VALOR NÃO PODE SER ALTERADO APÓS A ATRIBUIÇÃO INICIAL.
- var É UMA VARIAL ANTIGA NÃO USAR ELA MAIS

// TIPOS DE DADOS:
-STRING:->TEXTOS, POSSO UTILIZAR ASPAS DUPLAS (QUE NÃO PERMITE PULAR LINHAS)
- POSSO UTILIZAR ASPAS SIMPLES (QUE NÃO PERMITE PULAR LINHAS)
 -POSSO UTILIZAR CRASE (TAMBEM CHAMADA: TEMPLATE LITERALS OU TEMPLATE STRING) QUE PERMITE QUE EU PULE LINHAS ENTRE OUTRAS CONFIGURAÇÃOS
 SEQUÊNCIA DE CARACTERES, EXEMPLO: "FREITAS", 'FREITAS'
DENTRO DO TEMPLETE CRASE EU POSSO POR O SIMBOLO DO DOLAR MAIS OS BIGODINHOS ${VARIAVEL} PARA INSERIR VARIÁVEIS DENTRO DO TEXTO.


 -NUMBER: NÚMEROS INTEIROS OU DECIMAIS, EXEMPLO: 42, 3.14 TAMBEM PODEMOS USAR NOTAÇÃO CIENTIFICA 
 EXEMPLO: 1.5e+10 (QUE É IGUAL A 15000000000) OU DIVIDIR, SOMAR, MULTIPLICAR, ETC.

 -BOOLEAN: VALORES VERDADEIRO OU FALSO, EXEMPLO: true, false

 OBJETOS: É UMA COLEÇÃO DE DADOS ONDE EU POSSO POR MUITAS VARIAVEIS DENTRO DE UM MESMO LUGAR. EXEMPLO: CONST = { NOME: "DANIEL", IDADE: 42, 
 TRABALHO: "DESENVOLVEDOR"   ETC.}
DENTRO DE UM OBJETO EU POSSO CRIAR VARIOS OBJETOS: EXEMPLO: CONST PESSOA = { NOME: "DANIEL", DETALHES: { IDADE: 42, TRABALHO: "DESENVOLVEDOR" } }
TAMBEM POSSO DENTRO DO CONSOLE.LOG CHAMAR UMA VARIALVEL ESPECIFICA USANDO O NOME DO OBJETO + PONTO + NOME DA VARIAVEL EXEMPLO: CONSOLE.LOG
(PESSOA.DETALHES.IDADE) ISSO VAI MOSTRAR APENAS A IDADE NO CONSOLE.
MESMO USANDO O CONST EU POSSO MUDAR ALGUMAS INFORMAÇÕES EXEMPLO: NOME DO OBJETO + PONTO + NOME DA VARIAVEL = "NOVO VALOR" 
/ NOME.DANIEL= "MARIA" ISSO VAI MUDAR O NOME DENTRO DO OBJETO, MAS EU NÃO POSSO REATRIBUIR O OBJETO TODO EXEMPLO: 
PESSOA = { OUTRO OBJETO } ISSO VAI DAR ERRO.


NULL & UNDEFINED: NULL É QUANDO O PROGRAMADOR INDICA QUE DETERMINADA VARIÁVEL NÃO TEM VALOR, É NULA. UNDEFINED É QUANDO UMA VARIÁVEL FOI DECLARADA, 
MAS AINDA NÃO FOI ATRIBUÍDO NENHUM VALOR A ELA, OU O PROGRAMADOR COMETEU ALGUM ERRO. EXEMPLO: LET NOME; 
(A VARIÁVEL NOME ESTÁ INDEFINIDA, POIS NÃO TEM VALOR ATRIBUÍDO A ELA AINDA).

ARRAYS TAMBEM PODE SER CHAMADO DE (VETORES) SÃO USADOS PARA ARMAZENAR VÁRIOS VALORES EM UMA ÚNICA VARIÁVEL. 
EXEMPLO: LET FRUTAS = ["MAÇÃ", "BANANA", "LARANJA"];
POSSO ACESSAR CADA ITEM DO ARRAY USANDO O INDICE, EXEMPLO: CONSOLE.LOG(FRUTAS[0]) ISSO VAI MOSTRAR "MAÇÃ" NO CONSOLE.
O ARRY FUNCIONA COMO UMA CAIXA QUE PODE CONTER VÁRIOS ITENS DENTRO DELA.

IF & ELSE.
IF É UMA ESTRUTURA DE CONTROLE QUE PERMITE EXECUTAR UM BLOCO DE CÓDIGO SE UMA CONDIÇÃO FOR VERDADEIRA.
EXEMPLO:
IF (SE) FOR SIM FAÇA ISSO { CÓDIGO A SER EXECUTADO }
ELSE (SENÃO) FAÇA ISSO { CÓDIGO A SER EXECUTADO SE A CONDIÇÃO FOR FALSA }

OPERADORES DE COMPARAÇÕES:
> (MAIOR QUE)
< (MENOR QUE)
>= (MAIOR OU IGUAL A)
<= (MENOR OU IGUAL A)
== (IGUAL A)
=== (EXATAMENTE IGUAL A, VERIFICA TAMBÉM O TIPO DE DADO)
!= (DIFERENTE DE)
!== (EXATAMENTE DIFERENTE DE, VERIFICA TAMBÉM O TIPO DE DADO).

EXEMPLO DE USO DO IF: if(condição é o que esta dentro do parentes) EXECUÇÃO É O QUE ESTA DENTRO DOS BIGODINHOS "CHAVES {}" 
{se esta condição for verdadeira, execute este código}. exemplo: if(se a nota for >ou igual a 10) 
{então mostre no console "Aprovado"} 
else {senão mostre no console "Reprovado"}.

Function / Função: É UM BLOCO DE CÓDIGO PROJETADO PARA EXECUTAR UMA TAREFA ESPECÍFICA. Porem só aparece quando solicitadada. EXEMPLO DE UMA FUNÇÃO SIMPLES:
function saudacao() {
  console.log("Olá, bem-vindo ao meu site!");
}
  Para criar uma Functions precisamos por os parenteses () e as chaves {}.
  PARA CHAMAR A FUNÇÃO E EXECUTAR O CÓDIGO DENTRO DELA, BASTA POR O NOME DA FUNÇÃO SEGUIDO DE PARÊNTESES: saudacao();

Dom: Document Object Model (DOM) Uma arvore de elementos de uma site, É UMA INTERFACE DE PROGRAMAÇÃO PARA DOCUMENTOS HTML E XML. ELE REPRESENTA A PÁGINA DE FORMA QUE OS PROGRAMAS PODEM MUDAR 
A ESTRUTURA, ESTILO E CONTEÚDO DO DOCUMENTO. EXEMPLO: PARA ACESSAR UM ELEMENTO HTML PELO ID USAMOS:  document.getElementById("meuElementoID");

Para linkar o arquivo JS no HTML usamos a tag <script> EXEMPLO:
<script src="caminho/para/seu/arquivo.js"></script> eu pososo por essa tag no final do body ou no head. tambem posso por mais de um arquivo JS no HTML.

GeteElementById: É UM MÉTODO DO OBJETO DOCUMENT QUE RETORNA O ELEMENTO QUE TEM O ID ESPECIFICADO. EXEMPLO:
document.getElementById("meuElementoID"); ISSO VAI RETORNAR O ELEMENTO HTML COM O ID "meuElementoID".
para chamar este elemento dentro do html eu preciso usar aseguinte sintaxe: document + ponto + geteElementById + parenteses com o id entre aspas.
let elemento = document.getElementById("meuElementoID");
console.log(elemento); ISSO VAI MOSTRAR NO CONSOLE O ELEMENTO HTML COM O ID "meuElementoID".

GetElementsByClassName: É UM MÉTODO DO OBJETO DOCUMENT QUE RETORNA UMA COLEÇÃO DE TODOS OS ELEMENTOS COM A CLASSE ESPECIFICADA. EXEMPLO:
document.getElementsByClassName("minhaClasse"); ISSO VAI RETORNAR TODOS OS ELEMENTOS HTML COM A CLASSE "minhaClasse".
para chamar estes elementos dentro do html eu preciso usar a seguinte sintaxe: document + ponto + getElementsByClassName + parenteses com a classe entre aspas.
let elementos = document.getElementsByClassName("minhaClasse");
console.log(elementos); ISSO VAI MOSTRAR NO CONSOLE UMA COLEÇÃO DE ELEMENTOS HTML COM A CLASSE "minhaClasse".

GetElementsByTagName: É UM MÉTODO DO OBJETO DOCUMENT QUE RETORNA UMA COLEÇÃO DE TODOS OS ELEMENTOS COM A TAG ESPECIFICADA. EXEMPLO:
document.getElementsByTagName("div"); ISSO VAI RETORNAR TODOS OS ELEMENTOS HTML COM A TAG "div".
para chamar estes elementos dentro do html eu preciso usar a seguinte sintaxe: document + ponto + getElementsByTagName + parenteses com a tag entre aspas.
let divs = document.getElementsByTagName("div");
console.log(divs); ISSO VAI MOSTRAR NO CONSOLE UMA COLEÇÃO DE ELEMENTOS HTML COM A TAG "div".

GetElementsByName: É UM MÉTODO DO OBJETO DOCUMENT QUE RETORNA UMA COLEÇÃO DE TODOS OS ELEMENTOS COM O ATRIBUTO NAME ESPECIFICADO. EXEMPLO:
document.getElementsByName("meuNome"); ISSO VAI RETORNAR TODOS OS ELEMENTOS HTML COM O ATRIBUTO NAME "meuNome".
para chamar estes elementos dentro do html eu preciso usar a seguinte sintaxe: document + ponto + getElementsByName + parenteses com o name entre aspas.
let elementosNome = document.getElementsByName("meuNome");
console.log(elementosNome); ISSO VAI MOSTRAR NO CONSOLE UMA COLEÇÃO DE ELEMENTOS HTML COM O ATRIBUTO NAME "meuNome".

QuerySelector: É UM MÉTODO DO OBJETO DOCUMENT QUE RETORNA O PRIMEIRO ELEMENTO QUE CORRESPONDE A UM SELETOR CSS ESPECIFICADO. EXEMPLO:
document.querySelector(".minhaClasse"); ISSO VAI RETORNAR O PRIMEIRO ELEMENTO HTML COM A CLASSE "minhaClasse".
para chamar este elemento dentro do html eu preciso usar a seguinte sintaxe: document + ponto + querySelector + parenteses com o seletor CSS entre aspas.
let elementoQuery = document.querySelector(".minhaClasse");
console.log(elementoQuery); ISSO VAI MOSTRAR NO CONSOLE O PRIMEIRO ELEMENTO HTML COM A CLASSE "minhaClasse".

QuerySelectorAll: É UM MÉTODO DO OBJETO DOCUMENT QUE RETORNA UMA COLEÇÃO DE TODOS OS ELEMENTOS QUE CORRESPONDEM A UM SELETOR CSS ESPECIFICADO. EXEMPLO:
document.querySelectorAll("div"); ISSO VAI RETORNAR TODOS OS ELEMENTOS HTML COM A TAG "div".
para chamar estes elementos dentro do html eu preciso usar a seguinte sintaxe: document + ponto + querySelectorAll + parenteses com o seletor CSS entre aspas.
let elementosQueryAll = document.querySelectorAll("div");
console.log(elementosQueryAll); ISSO VAI MOSTRAR NO CONSOLE UMA COLEÇÃO DE ELEMENTOS HTML COM A TAG "div".



*/

let nome = "Freitas";